// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DeepCleaner
{
    internal sealed partial class Vsix
    {
        public const string Id = "DeepCleaner.c2c9c43c-e52f-4011-b777-0dfb1bd8da88";
        public const string Name = "DeepCleaner";
        public const string Description = @"Add command to delete bin and obj with clean and rebuildAdd ";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Vincent Chapront";
        public const string Tags = "";
    }
}
