// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DeepCleaner
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string DeepCleanerString = "1ebd075e-2c78-4ce2-bdb7-df5072167287";
        public static Guid DeepCleaner = new Guid(DeepCleanerString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int DeepCleanSolutionCommand = 0x0100;
        public const int DeepRebuildSolutionCommand = 0x0101;
        public const int DeepCleanProjectCommand = 0x0102;
        public const int DeepRebuildProjectCommand = 0x0103;
    }
}